services:
  cam-10_145_80_41-p554:
    image: alpine/socat
    container_name: cam-10_145_80_41-p554
    command: TCP-LISTEN:9001,fork TCP:10.145.80.41:554
    network_mode: host
    restart: unless-stopped
  cam-10_145_80_51-p554:
    image: alpine/socat
    container_name: cam-10_145_80_51-p554
    command: TCP-LISTEN:9002,fork TCP:10.145.80.51:554
    network_mode: host
    restart: unless-stopped
networks:
  camera-net:
    driver: bridge
