services:
  rtsp-proxy:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-proxy-server
    restart: unless-stopped
    ports:
    - 8554:8554
    - 8443:8443
    - 8888:8888
    volumes:
    - ./mediamtx.yml:/mediamtx.yml
    networks:
    - camera-net
  worker-cam1:
    build:
      context: ..
      dockerfile: docker_files/Dockerfile
    container_name: worker-cam1
    restart: on-failure
    depends_on:
    - rtsp-proxy
    environment:
    - RTSP_URL=rtsp://rtsp-proxy:8554/cam1
    - CAMERA_ID=cam1
    volumes:
    - ./capturas:/app/capturas
    networks:
    - camera-net
  worker-cam2:
    build:
      context: ..
      dockerfile: docker_files/Dockerfile
    container_name: worker-cam2
    restart: on-failure
    depends_on:
    - rtsp-proxy
    environment:
    - RTSP_URL=rtsp://rtsp-proxy:8554/cam2
    - CAMERA_ID=cam2
    volumes:
    - ./capturas:/app/capturas
    networks:
    - camera-net
  worker-cam3:
    build:
      context: ..
      dockerfile: docker_files/Dockerfile
    container_name: worker-cam3
    restart: on-failure
    depends_on:
    - rtsp-proxy
    environment:
    - RTSP_URL=rtsp://rtsp-proxy:8554/cam3
    - CAMERA_ID=cam3
    volumes:
    - ./capturas:/app/capturas
    networks:
    - camera-net
networks:
  camera-net:
    driver: bridge
