# (A tag 'version' não é mais necessária, como vimos)
services:
  rtsp-proxy:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-proxy-server
    restart: unless-stopped
    ports:
      # Publica a porta do stream RTSP no seu PC
      # (Formato: "Porta_do_Seu_PC:Porta_do_Container")
      - "8554:8554" 
      
      # Opcional: Publica a porta de visualização Web (WebRTC)
      # Você pode testar no navegador em http://localhost:8443
      - "8443:8443"
      
      # Opcional: Porta HLS (para players da Apple)
      - "8888:8888"
      
    volumes:
      # Mapeia o arquivo de configuração que criamos
      # para dentro do container
      - ./mediamtx.yml:/mediamtx.yml